### ISSUE TITLE
Login with Google button

### ISSUE THREAD

**Issue by BRO3886** [GDGVIT/pipo-frontend#14]
refer [this](https://developers.google.com/identity/branding-guidelines) to see how the button should be

I think instead of the text saying login PiPo using G, it can just say Login/Sign-In with Google, along with it's "G" logo

**Comment by VisheshBansal** [comment]
@saikun0293 Please make sure it follows the Google Branding Guidelines

Link for your reference:
https://developers.google.com/identity/branding-guidelines
